/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Intro',
      items: ['Intro', "Author"],
    },
  ],

  projectsSidebar: [
    {
      type: 'category',
      label: 'Projetos',
      items: ['projects/Projects Overview'],
    },
  ],
   
  docsSidebar: [
    {
      type: 'category',
      label: 'Docs',
      items: ['programacao/python-basic', 'programacao/python-controlflow', 'programacao/python-functions', 'programacao/python-lists',
      'programacao/python-strings', 'programacao/sql-basic','math/statistics', 'data-science-foundations/data-science-fields',
      'data-science-foundations/data','computer-vision/color-spaces', 'computer-vision/introduction-cv', 'data-manipulation/data-importing'],
    },
  ],*/
};

module.exports = sidebars;
